
package IU;

import controladores.ControladorGestor;
import dominio.Gestor;
import dominio.Pedido;
import dominio.UnidadProcesadora;
import java.util.List;
import javax.swing.DefaultListModel;
import vistas.VistaGestor;
import vistas.VistaLoginGestor;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import logica.Fachada;


public class VentanaGestor extends javax.swing.JFrame implements VistaGestor{

    private ControladorGestor controlador;
    private Gestor gestor;
    private UnidadProcesadora up;
    
    public VentanaGestor(Gestor gestor) {
        initComponents();
        setLocationRelativeTo(null);
        this.gestor = gestor; 
        this.up = gestor.getUnidadProcesadora();
        lblEncabezado.setText("Gestor: " + gestor.getNombreCompleto() + " | Unidad: " + up.getNombre());
        
        this.controlador = new ControladorGestor(this, gestor);
        controlador.refrescarListar();        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEncabezado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPedidosPendientes = new javax.swing.JList();
        btnTomarPedido = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedidosTomados = new javax.swing.JTable();
        btnFinalizarPedido = new javax.swing.JButton();
        btnEntregarPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblMensajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblEncabezado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jScrollPane1.setViewportView(listPedidosPendientes);

        btnTomarPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTomarPedido.setText("Tomar Pedido");
        btnTomarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarPedidoActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(tblPedidosTomados);
        if (tblPedidosTomados.getColumnModel().getColumnCount() > 0) {
            tblPedidosTomados.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tblPedidosTomados.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tblPedidosTomados.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tblPedidosTomados.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        btnFinalizarPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFinalizarPedido.setText("Finalizar Pedido");
        btnFinalizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarPedidoActionPerformed(evt);
            }
        });

        btnEntregarPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEntregarPedido.setText("Entregar Pedido");
        btnEntregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarPedidoActionPerformed(evt);
            }
        });

        jLabel1.setText("Mensajes del sistema:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTomarPedido)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(btnFinalizarPedido)
                            .addGap(18, 18, 18)
                            .addComponent(btnEntregarPedido))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTomarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizarPedido)
                    .addComponent(btnEntregarPedido))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTomarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarPedidoActionPerformed
        //obtengo el indice seleccionado de la lista
        int sel = listPedidosPendientes.getSelectedIndex();
        
        //delego el en controlador
        controlador.tomarPedido(sel);
    }//GEN-LAST:event_btnTomarPedidoActionPerformed

    private void btnFinalizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarPedidoActionPerformed
        controlador.finalizarPedido(tblPedidosTomados.getSelectedRow());
    }//GEN-LAST:event_btnFinalizarPedidoActionPerformed

    private void btnEntregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarPedidoActionPerformed
        controlador.entregarPedido(tblPedidosTomados.getSelectedRow());
    }//GEN-LAST:event_btnEntregarPedidoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(controlador.logout(gestor)) this.dispose();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntregarPedido;
    private javax.swing.JButton btnFinalizarPedido;
    private javax.swing.JButton btnTomarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEncabezado;
    private javax.swing.JLabel lblMensajes;
    private javax.swing.JList listPedidosPendientes;
    private javax.swing.JTable tblPedidosTomados;
    // End of variables declaration//GEN-END:variables

     @Override
    public void mostrarEncabezado(String nomGestor, String unidadProcesadora) {
        lblEncabezado.setText("Gestor: "+ nomGestor + " | Unidad: " + unidadProcesadora);
    }

     @Override
    public void mostrarPedidosPendientes(List<Pedido> pendientes) {
        DefaultListModel<String> lista = new DefaultListModel<>();
        for(Pedido p : pendientes){
            lista.addElement(
                p.getItem().getNombre() +"- cliente: " + p.getNombreCliente()
                );
            }
            listPedidosPendientes.setModel(lista);
        }

        @Override
        public void mostrarPedidosTomados(List<Pedido> tomados) {
            String[] columnas = { "Nombre de Ítem", "Comentario", "Cliente", "Fecha/Hora", "Estado" };
            Object[][] datos = new Object[tomados.size()][columnas.length];
            for (int i = 0; i < tomados.size(); i++) {
                Pedido p = tomados.get(i);
                datos[i][0] = p.getItem().getNombre();
                datos[i][1] = p.getComentario();
                datos[i][2] = p.getNombreCliente();
                datos[i][3] = p.getFechaCreacion();
                datos[i][4] = p.getEstado();
            }
            tblPedidosTomados.setModel(new javax.swing.table.DefaultTableModel(datos, columnas));
        }

        @Override
        public void mostrarError(String mensaje) {
            lblMensajes.setText("<html>" + mensaje + "</html>");
        }
        
    }

    
 
