
package IU;

import controladores.ControladorLoginCliente;
import controladores.ControladorRealizarPedido;
import dominio.Categoria;
import dominio.Cliente;
import dominio.ItemMenu;
import dominio.Pedido;
import dominio.Servicio;
import java.util.ArrayList;
import logica.Fachada;
import vistas.VistaCliente;


public class VentanaCliente extends javax.swing.JFrame implements VistaCliente{

    private ControladorLoginCliente controladorLogin;
    
    private ControladorRealizarPedido controladorPedido;
    
    private ArrayList<Categoria> categorias;
    
    private Categoria categoriaActual;
    
    private Servicio servicio;
    
    private boolean pendienteConfirmacionDePago = false;
    
    public VentanaCliente(MenuDesarrollo padre, Servicio s) {
        initComponents();
        setLocationRelativeTo(padre);
        controladorLogin = new ControladorLoginCliente(this);
        this.setTitle("Esperando Acceso...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroCliente = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnAgregarPedido = new javax.swing.JButton();
        btnEliminarPedido = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtMontoTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaCategorias = new javax.swing.JList();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnConfirmarPedidos = new javax.swing.JButton();
        btnFinalizarServicios = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaItems = new javax.swing.JList();
        txtMensaje = new javax.swing.JLabel();
        btnConfirmarFinalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jScrollPane1.setViewportView(tblPedido);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Número de cliente:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        txtNumeroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroClienteActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogin.setText("Aceptar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnAgregarPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregarPedido.setText("Agregar Pedido");
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });

        btnEliminarPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminarPedido.setText("Eliminar Pedido");
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });

        txtMontoTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mensajes del sistema");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Identificarse");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Categorías");

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane3.setViewportView(txtComentario);

        listaCategorias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listaCategorias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaCategoriasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listaCategorias);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ítems");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Menú");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Pedidos del servicio");

        btnConfirmarPedidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConfirmarPedidos.setText("Confirmar Pedidos");
        btnConfirmarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPedidosActionPerformed(evt);
            }
        });

        btnFinalizarServicios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFinalizarServicios.setText("Finalizar Servicio");
        btnFinalizarServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarServiciosActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Comentario");

        jScrollPane5.setViewportView(listaItems);

        txtMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMensaje.setText("Ingrese su número de cliente y contraseña");

        btnConfirmarFinalizar.setText("Confirmar");
        btnConfirmarFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarFinalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnAgregarPedido)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnEliminarPedido))
                                        .addComponent(jLabel10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(52, 52, 52))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConfirmarPedidos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFinalizarServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfirmarFinalizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 1301, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMontoTotal)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(txtNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtNumeroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAgregarPedido)
                                    .addComponent(btnEliminarPedido))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmarPedidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConfirmarFinalizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMontoTotal)
                    .addComponent(btnFinalizarServicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensaje)
                    .addComponent(jLabel4))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroClienteActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String numCliente = txtNumeroCliente.getText().trim();
        String password = txtPassword.getText().trim();
        
        if(numCliente.isEmpty() || password.isEmpty()){
            mostrarError("Ingrese numero de clinte y contraseña.");
            return;
        }
        
        controladorLogin.loginCliente(numCliente, password);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnConfirmarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPedidosActionPerformed
        //freno para el boton de confirmar
        if(pendienteConfirmacionDePago){
            mostrarError("Primero pulse Confirmar para continuar.");
            return;
        }
        
        if(controladorPedido !=null){
        borrarMensaje();
        controladorPedido.confirmarServicio();
        }
        else{
            mostrarError("Debe Identificarse antes de confirmar pedidos.");
        }
    }//GEN-LAST:event_btnConfirmarPedidosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened

    private void listaCategoriasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaCategoriasValueChanged
        int catIndice = listaCategorias.getSelectedIndex();
        if (catIndice == -1) return; // 🛡️ evita el crash

        ArrayList<Categoria> categorias = Fachada.getInstancia().getCategorias();
        if (catIndice >= categorias.size()) return; // por si hay desfase

        categoriaActual = categorias.get(catIndice);
        cargarItemsCategoria(categoriaActual);
    }//GEN-LAST:event_listaCategoriasValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        //freno para el boton de confirmar
        if(pendienteConfirmacionDePago){
            mostrarError("Primero pulse Confirmar para continuar.");
            return;
        }       
        if(controladorPedido == null){
            mostrarError("Debe identificarse antes de realizar pedidos.");
            return;
        }
        borrarMensaje();
        controladorPedido.agregarPedido(listaItems.getSelectedIndex(), txtComentario.getText(), categoriaActual);
        
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed
        //freno para el boton de confirmar
        if(pendienteConfirmacionDePago){
            mostrarError("Primero pulse Confirmar para continuar.");
            return;
        }
        if(controladorPedido == null){
            mostrarError("Debe identificarse antes de eliminar pedidos.");
            return;
        }
        borrarMensaje();
        controladorPedido.eliminarPedido(tblPedido.getSelectedRow());
    }//GEN-LAST:event_btnEliminarPedidoActionPerformed

    private void btnFinalizarServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarServiciosActionPerformed
        //freno para el boton de confirmar
        if(pendienteConfirmacionDePago){
            mostrarError("Primero pulse Confirmar para continuar.");
            return;
        }
        
        
        if (controladorPedido != null) {
            controladorPedido.finalizarServicio();
        }else{
            mostrarError("Debe identificarse antes de finalizar el servicio.");
        }
    }//GEN-LAST:event_btnFinalizarServiciosActionPerformed

    private void btnConfirmarFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarFinalizarActionPerformed
        if(!pendienteConfirmacionDePago){
            mostrarError("No hay informacion pendiente para confirmar.");
            return;
        }
        // limpio la interfaz
        resetInterfaz();
        
        //vuelvo al estado inicial
        pendienteConfirmacionDePago = false; 
        mostrarMensaje("Ingrese numero de cliente y contraseña");
    }//GEN-LAST:event_btnConfirmarFinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JButton btnConfirmarFinalizar;
    private javax.swing.JButton btnConfirmarPedidos;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JButton btnFinalizarServicios;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JList listaCategorias;
    private javax.swing.JList listaItems;
    private javax.swing.JTable tblPedido;
    private javax.swing.JTextArea txtComentario;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JLabel txtMontoTotal;
    private javax.swing.JTextField txtNumeroCliente;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarCategorias(ArrayList<Categoria> categorias) {
        ArrayList<String> categoriasString = new ArrayList();
        for(Categoria c: categorias){
            categoriasString.add(c.getNombre());
        }
        listaCategorias.setListData(categoriasString.toArray());
    }
    
    @Override
    public void loginExitoso(Cliente cliente) {
        Servicio servicio = Fachada.getInstancia().comenzarServicio(cliente);
        this.servicio = servicio;
        controladorPedido = new ControladorRealizarPedido(this, servicio);
        txtMensaje.setText("Bienvenido - "+ servicio.getCliente().getNombreCompleto());
        setTitle("Bienvenido - "+ servicio.getCliente().getNombreCompleto());
        cargarCategorias(Fachada.getInstancia().getCategorias());
    }

    @Override
    public void mostrarError(String message) {
       txtMensaje.setText("<html>" + message + "</html>");
    }

    @Override
    public void mostrarMensaje(String message) {
        txtMensaje.setText("<html>" + message + "</html>");
    }
    
    
    @Override
    public void cargarItemsCategoria(Categoria categoria) {
        ArrayList<ItemMenu> items = categoria.getItemsMenu();
        ArrayList<String> itemsString = new ArrayList();
        for(ItemMenu i:items){
            if(i.estaDisponible()) itemsString.add(i.getNombre() + " - $" + i.getPrecioUnitario());            
        }
        listaItems.setListData(itemsString.toArray());
        
    }
    
    
    @Override
    public void mostrarPedidosServicio(ArrayList<Pedido> pedidos) {
    // Esto puede cambiar según cómo quieras mostrar los pedidos
    // Por ejemplo, usando una JTable

    String[] columnas = {"Ítem", "Comentario", "Estado", "Unidad Procesadora", "Gestor", "Precio"};
    String[][] datos = new String[pedidos.size()][6];

    for (int i = 0; i < pedidos.size(); i++) {
        Pedido p = pedidos.get(i);
        datos[i][0] = p.getItem().getNombre();
        datos[i][1] = p.getComentario();
        datos[i][2] = p.getEstado().toString();
        datos[i][3] = p.getItem().getUnidadProcesadora().getNombre();
        datos[i][4] = (p.getGestor() != null) ? p.getGestor().getNombreCompleto() : "Sin asignar";
        datos[i][5] = "$" + p.getItem().getPrecioUnitario();
    }
    
    tblPedido.setModel(new javax.swing.table.DefaultTableModel(datos, columnas));
    
     if (servicio == null || pedidos.isEmpty()) {
        txtMontoTotal.setText("");
    } else {
        txtMontoTotal.setText("Monto total: $" + this.servicio.getTotal());
    }
}

 
    private void borrarMensaje(){
        txtMensaje.setText("");
    }
    
    public void resetInterfaz(){
        //desengancho el observador si es que existe
        if(servicio != null && controladorPedido != null){
            servicio.quitarObservador(controladorPedido);
        }
        
        //rompo las referencias
        this.servicio = null;
        this.controladorPedido = null;
        
        // limpiar visualmente
        txtNumeroCliente.setText("");
        txtPassword.setText("");
        
        listaCategorias.clearSelection();
        categoriaActual = null;
        listaItems.setListData(new Object[0]);
        
        tblPedido.setModel(new javax.swing.table.DefaultTableModel()); // esto limpia la tabla
        
        txtComentario.setText("");
        txtMontoTotal.setText("");
        txtMensaje.setText("Ingrese su numero de cliente y contraseña.");
    }

    @Override
    public void marcarPagoPendiente() {
        pendienteConfirmacionDePago = true;
    }
    
    
}
